_BASE_SELECT = """
SELECT
    rownum fila,
    S.SR_NUM AS NRO_DE_INCIDENTE,
    S.SR_CST_NUM AS NUMERO_CUN,
    A.X_EVE_INTEG_ID AS ID_DE_SERVICIO,
    S.SR_STAT_ID AS ESTADO,
    S.ACT_OPEN_DT - (5/24) AS FECHA_DE_APERTURA,
    S.TT_TYPE_CD AS TIPO_INCIDENTE,
    XM.NAME AS ID_INFRAESTRUCTURA,
    XM.ATTRIB_18 AS "DAÑOS_ABIERTOS_POR_ELEMENTO",
    N.SYMPTOM_CD AS NATURALEZA,
    XM.ATTRIB_03 AS TIPO_INFRAESTRUCTURA,
    XM.ATTRIB_14 AS UMBRAL_FALLA,
    S.UND_MFG_WRNTY_FLG AS GARANTIA_DE_REPARACION,
    S.COMP_UND_WRNTY_FLG AS GARANTIA_DE_INSTALACION,
    S.ROOT_CAUSE_CD AS CAUSA,
    P.NAME AS PRODUCTO,
    S.X_TECNOLOGIA AS "TECNOLOGÍA",
    D.DESCRIPTOR AS BARRIO,
    D.CITY AS CIUDAD,
    D.PROVINCE AS DEPARTAMENTO,
    C.DUNS_NUM AS NRO_DOC_CUENTA,
    C.NAME AS NOMBRE_CUENTA,
    XM.ATTRIB_40 AS ID_EQUIPO,
    XM.ATTRIB_41 AS TIPO_EQUIPO,
    XM.ATTRIB_06 AS ESTADO_EQUIPO,
    XM.ATTRIB_35 AS MAC_EQUIPO,
    XM.ATTRIB_36 AS MAC2_EQUIPO,
    XM.ATTRIB_37 AS MARCA_EQUIPO,
    XM.ATTRIB_07 AS MODELO_EQUIPO,
    XM.ATTRIB_46 AS ID_UNE,
    XM.ATTRIB_15 AS SECUENCIA,
    XM.ATTRIB_05 AS TIPO_LOCALIZACION,
    S.RESOLUTION_CD AS CODIGO_CIERRE,

    (SELECT CC.INTEGRATION_ID
       FROM SIEBEL.S_SRV_REQ CC, SIEBEL.S_SR_REL R
      WHERE S.ROW_ID = R.REL_SR_ID(+)
        AND R.SR_ID = CC.ROW_ID(+)
        AND CC.TT_TYPE_CD = 'Causa Común Conocida'
        AND (CC.SR_STAT_ID = 'Abierto' OR CC.SR_STAT_ID = 'En progreso')
        AND ROWNUM <= 1) AS NRO_TIQUETE_TT,

    F2.STR_EFFECTIVE_DT AS "FECHA_CIERRE_TECNICO_DAÑO",
    S.NEW_SEC_ANSWR AS UEN_CALCULADA,
    CO.FST_NAME || ' ' || CO.LAST_NAME AS NOMBRE_COMPLETO_CONTACTO,
    CO.HOME_PH_NUM AS NRO_TEL_PARTICULAR,
    CO.CELL_PH_NUM AS NRO_TEL_MOVIL,
    D.ADDR AS DIRECCION,
    D.LANDLORD_PH_NUM AS CODIGO_FAMILIAR,
    A.X_UNE_ID_LEGADO AS ID_LEGADO,
    S.SR_SUB_STAT_ID AS SUB_ESTADO,
    S.X_DESCRIPCION AS "DESCRIPCIÓN",
    G.NAME AS GRUPO,

    (SELECT PLAN.NAME
       FROM SIEBEL.S_ASSET COMP, SIEBEL.S_PROD_INT PLAN
      WHERE A.ROW_ID = COMP.PAR_ASSET_ID(+)
        AND COMP.PROD_ID = PLAN.ROW_ID(+)
        AND PLAN.TYPE = 'Plan comercial'
        AND COMP.STATUS_CD = 'Activo'
        AND ROWNUM <= 1) AS PLAN_COMERCIAL,

    U.EXCHNG_PROF_NAME AS LOGIN_OPENSER

FROM SIEBEL.S_PROD_INT     P,
     SIEBEL.S_ORG_EXT      C,
     SIEBEL.S_SRV_REQ      S,
     SIEBEL.S_ASSET        A,
     SIEBEL.S_CONTACT      CO,
     SIEBEL.S_ADDR_PER     D,
     SIEBEL.S_SYMPTOM      N,
     SIEBEL.S_USER         U,
     SIEBEL.S_ORG_EXT      G,
     SIEBEL.S_SRV_REQ2_FNX F2,
     SIEBEL.S_SRV_REQ_XM   XM

WHERE S.ASSET_ID = A.ROW_ID(+)
  AND A.SERV_ACCT_ID = C.ROW_ID(+)
  AND A.OWNER_ACCNT_ID = U.X_EVE_ACCNT_ID(+)
  AND S.OWNER_OU_ID = G.PAR_ROW_ID(+)
  AND A.PROD_ID = P.ROW_ID(+)
  AND S.PR_SYMPTOM_CD = N.ROW_ID(+)
  AND S.OU_ADDR_ID = D.ROW_ID(+)
  AND XM.PAR_ROW_ID = S.ROW_ID
  AND S.ROW_ID = F2.PAR_ROW_ID(+)
  AND S.CST_CON_ID = CO.ROW_ID(+)
  AND S.TT_TYPE_CD = 'Queja Daño'
  AND (XM.TYPE = 'INFR_ASSET' OR S.X_TECNOLOGIA = 'DTH')
  AND (S.SR_STAT_ID = 'Abierto' OR S.SR_STAT_ID = 'En progreso')
  AND ROWNUM <= 1000
"""

# Todos los activos — ROWNUM <= 1000 es el placeholder que main.py reemplaza
INCIDENTS_QUERY = _BASE_SELECT

# Ultimas ~10h Colombia — ALL_ROWS hint + SR_STAT_DT para performance
INCIDENTS_QUERY_10H = (
    _BASE_SELECT
    .replace(
        "SELECT\n    rownum fila,",
        "SELECT\n/*+ ALL_ROWS */   rownum fila,",
    )
    .replace(
        "S.ACT_OPEN_DT - (5/24) AS FECHA_DE_APERTURA,",
        "S.SR_STAT_DT - (5/24) AS FECHA_DE_APERTURA,",
    )
    .replace(
        "AND ROWNUM <= 1000",
        "AND (S.SR_STAT_DT - (5/24)) > SYSDATE - (10/24)\n  AND ROWNUM <= 1000",
    )
)

# Ultimas ~24h Colombia — misma formula con (24/24)
INCIDENTS_QUERY_24H = (
    _BASE_SELECT
    .replace(
        "SELECT\n    rownum fila,",
        "SELECT\n/*+ ALL_ROWS */   rownum fila,",
    )
    .replace(
        "S.ACT_OPEN_DT - (5/24) AS FECHA_DE_APERTURA,",
        "S.SR_STAT_DT - (5/24) AS FECHA_DE_APERTURA,",
    )
    .replace(
        "AND ROWNUM <= 1000",
        "AND (S.SR_STAT_DT - (5/24)) > SYSDATE - (24/24)\n  AND ROWNUM <= 1000",
    )
)

# Personalizada — ventana variable en horas; HOURS_PH se reemplaza en main.py
INCIDENTS_QUERY_CUSTOM = (
    _BASE_SELECT
    .replace(
        "SELECT\n    rownum fila,",
        "SELECT\n/*+ ALL_ROWS */   rownum fila,",
    )
    .replace(
        "S.ACT_OPEN_DT - (5/24) AS FECHA_DE_APERTURA,",
        "S.SR_STAT_DT - (5/24) AS FECHA_DE_APERTURA,",
    )
    .replace(
        "AND ROWNUM <= 1000",
        "AND (S.SR_STAT_DT - (5/24)) > SYSDATE - (HOURS_PH/24)\n  AND ROWNUM <= 1000",
    )
)
